---
abstract: 'Calculate geographic distances.'
author:
  - 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: GIS-Distance
no_index:
  directory:
    - inc
    - t
recommends:
  GIS::Distance::Fast: 0
  Geo::Ellipsoid: 0.902
  Test::Pod: 1.22
requires:
  Class::Measure: 0
  Math::Complex: 0
  Moose: 0.39
  perl: 5.8.3
version: 0.03
